name: CI

on:
  push:
    branches:
      - source
  issues:
    types:
      [
        opened,
        closed,
        edited,
        milestoned,
        labeled,
        unlabeled,
        reopened,
        demilestoned,
      ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Download Issue and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm install --no-frozen-lockfile --config.dangerously-allow-all-builds=true
          pnpm action
          pnpm build
          pnpm run deploy
