name: Build blog
on:
  push:
    branches: [ master ]
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - run: npm install hexo-cli -g
      - run: npx -p npm@6 npm ci
      - run: hexo generate
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          CLEAN: true
          BRANCH: gh-pages
          FOLDER: public/
